### ISSUE TITLE
hang on bad bytes

### ISSUE THREAD

**Issue by Kyle-Kyle** [Boyan-MILANOV/ropium#31]
by doing
~~~
(ropium)> badbytes 115
(ropium)> find rax = 0x68732f6e69622f
~~~
`ropium` hangs. The target binary is the libc from ubuntu 18.04

**Comment by Kyle-Kyle** [comment]
This should be able to be done through `xor`. Probably `ropium` doesn't have the ability to do `xor`?

**Comment by Boyan-MILANOV** [comment]
Hey! 

It is indeed planned to add some compiling rules enabling to set registers by also using arithmetic and logic operations (ADD,SUB,XOR,AND,OR,...). I'll try to work on that ASAP in parallel with Aarch64 support :) 

ROPium hangs on the query because it can't find a suitable ropchain. I just added a feature to enable users to use **Ctrl-C** to stop the search when it takes too long ;)
